### ISSUE TITLE
Add IE warning pop-up by default

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/generator-wim#101]
Include code that adds a warning for users of IE to use the application in a modern browser.

**Comment by lprivette** [comment]
Would it work like this?: 

User arrives at site > code checks to see if user is using IE or not > if so, a popup comes up. if not, nothing happens.

**Comment by njestes** [comment]
Yeah, we have this is a couple other apps already. Blake did it in WLERA and I used his code in sw-trends.
