### ISSUE TITLE
Add User Guide

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/generator-wim#116]
Enough of our interface is standard that many entries could be filled out.
Inspiration - swtrends:
![image](https://cloud.githubusercontent.com/assets/12058013/23767339/404b8d32-04d6-11e7-97c0-eba9411f6b7a.png)

**Comment by lprivette** [comment]
Do we want this to be in both the Full and Lite versions? or just the Full?

**Comment by HansVraga** [comment]
Just the Full.

**Comment by lprivette** [comment]
Fix is in Develop
