### ISSUE TITLE
Opensourcing our layers handling logic

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/generator-wim#13]
Just a thought: once we update (bootstrapify) our layers handling logic for the esri track, i.e. the code currently in _layers.js, maybe we separate that out into a little package and put it in a public repo? Someone else could use a thing that takes a simple JSON layers object and assembles layers toggle and legend divs automatically. Just trying to think with an open source kind of mind.

**Comment by marsmith** [comment]
closing this, we're wokring for this in v2
