### ISSUE TITLE
Fix geo search issues

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/generator-wim#56]
Modal closes when selecting from autopopulated list. Have to open again and click to search. 

Also fix to zoom to a more appropriate zoom level when returning a result. Currently just pans over to result

**Comment by marsmith** [comment]
implement TX Geosearch:
https://txpub.usgs.gov/dss/search_api/2.0/doc/

**Comment by HansVraga** [comment]
To handle the mix of extent and point data:
https://github.com/USGS-WiM/fim-js/blob/staging/src/scripts/core.js#L793-L819

**Comment by HansVraga** [comment]
Also, some other changes:

- [x] Change button from "Geosearch" to "Find Location"

- [ ] Include help text and credit link in the modal - something like:
![image](https://cloud.githubusercontent.com/assets/12058013/24103748/9ea8201a-0d56-11e7-9194-46af045b5f4b.png)

**Comment by lprivette** [comment]
added tx geosearch to esri and leaflet builds.
