### ISSUE TITLE
Idea: A branch for auto-parsing a layers object and a branch for custom dev

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/generator-wim#81]
One of the strengths of the app template the generator spits out is that it is built to automatically parse the JSON-formatted layers object we give it. I think we all agree with that. But there will also be many times where the developer will choose to abandon that layers object/auto-parsing approach for a conventional custom code job. For instance, I did that for the WLERA application. 

The generated app template provides the page layout/scaffolding/styling which is still needed even when abandoning the layers object parsing model. I am floating the idea that we have one branch which contains the functions that build all the things from a layers object (the current master branch of this repo is like that), and another, stripped down branch which has all the scaffolding and maybe just a few sample layers declared the old fashioned way, in the core.js file. 

Stripping out the parsing functions and going custom isn't hard for a developer to do after generating a new template, as I did with WLERA, but I thought it might be good to formalize and automate the process a bit. 

Everyone welcome to discuss, but especially looking for input from @njestes @marsmith @esmyers

**Comment by marsmith** [comment]
We have implemented the 'lite' and 'full' versions in v2 to handle this
