### ISSUE TITLE
How do the js and css get piped the uglify function in our gulp config?

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/generator-wim#87]
This question directed primarily at @marsmith:

I am trying to truly understand gulp, and the gulpfile, rather than just dumbly using it like I have been. I have a question about something I see in the gulpfile that comes from the generator.

I notice you have the gulp uglify plugin running within the 'html' gulp task. See snippet below, gulpfile.js

``` javascript
// HTML
gulp.task('html', ['styles', 'scripts', 'icons'], function () {
    var jsFilter = $.filter('**/*.js');
    var cssFilter = $.filter('**/*.css');

    return gulp.src('src/*.html')
        .pipe($.useref.assets())
        .pipe(jsFilter)
        .pipe($.uglify())
        .pipe(jsFilter.restore())
        .pipe(cssFilter)
        .pipe($.csso())
        .pipe(cssFilter.restore())
        .pipe($.useref.restore())
        .pipe($.useref())
        //.pipe(rename({ extname: '.min.js' }))
        .pipe(gulp.dest('build'))
        .pipe($.size());
});
```

I understand the `'html'` to be the name of the task, and the `['styles', 'scripts', 'icons']` to be the dependencies that must run before this task runs. I'm getting a lot of my info from [this article](http://www.smashingmagazine.com/2014/06/building-with-gulp/). 

So I am wondering both why and how the uglification/minification of the javascript and css is taking place within the 'html' gulp task. It seems like what is happening is you are using the [gulp-filter plugin](https://www.npmjs.com/package/gulp-filter/) to set `jsFilter` and `cssFilter` variables which look for files ending in `.js` and `.css`, respectively. Then I see you do `.pipe(jsFilter.restore())` to pipe through the uglified version to the build folder. But I don't understand what in this snippet above actually tells gulp to minify the js and css. I don't get how they are connected. 

The snippet below, from an intro to gulp article, has a pipe nested in a gulp.src function, which makes sense. In ours, I don't see how gulp knows to pipe the css and js to the uglify function because there is no gulp.src definition. I am guessing it somehow happens through the dependencies array argument? Those all have a gulp.src in them to define the path and file extension, so maybe that ports through somehow?

The intro to gulp article linked above does something like this to minify:

``` javascript
gulp.task('minify', function () {
   gulp.src('js/app.js')
      .pipe(uglify())
      .pipe(gulp.dest('build'))
});
```

Which seems more intuitive. I don't mean to be obnoxious - not just throwing stones here, but just curious if there's a reason it is the way it is, and how it actually works.

**Comment by marsmith** [comment]
The magic happens here:

``` 
return gulp.src('src/*.html')
        .pipe($.useref.assets())
```
so this part finds the index.html file, and looks for the useref comment blocks.  After that the js and css files are piped in
